// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMy0USIqQqyntP0AcANhKONS1nMwIQlok',
    appId: '1:592259731924:web:7432c490848c449ad74641',
    messagingSenderId: '592259731924',
    projectId: 'chatapptute-c2a7d',
    authDomain: 'chatapptute-c2a7d.firebaseapp.com',
    storageBucket: 'chatapptute-c2a7d.firebasestorage.app',
    measurementId: 'G-T5JLXZV5M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2o5Ks2vufbV6hxAZwFUM4O4VKYTBENm4',
    appId: '1:592259731924:android:d9a9c453ae9172f4d74641',
    messagingSenderId: '592259731924',
    projectId: 'chatapptute-c2a7d',
    storageBucket: 'chatapptute-c2a7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2bKTNhZxvB8W-DeJaD-VLrCm97_-12VY',
    appId: '1:592259731924:ios:c15a03bec03a433bd74641',
    messagingSenderId: '592259731924',
    projectId: 'chatapptute-c2a7d',
    storageBucket: 'chatapptute-c2a7d.firebasestorage.app',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2bKTNhZxvB8W-DeJaD-VLrCm97_-12VY',
    appId: '1:592259731924:ios:c15a03bec03a433bd74641',
    messagingSenderId: '592259731924',
    projectId: 'chatapptute-c2a7d',
    storageBucket: 'chatapptute-c2a7d.firebasestorage.app',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMy0USIqQqyntP0AcANhKONS1nMwIQlok',
    appId: '1:592259731924:web:28ada4a7cd965355d74641',
    messagingSenderId: '592259731924',
    projectId: 'chatapptute-c2a7d',
    authDomain: 'chatapptute-c2a7d.firebaseapp.com',
    storageBucket: 'chatapptute-c2a7d.firebasestorage.app',
    measurementId: 'G-Z34CX2S84S',
  );
}
